"""empty message

Revision ID: 0934b7ee9011
Revises: 5d66ed7b914e
Create Date: 2024-03-18 16:58:49.356495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0934b7ee9011'
down_revision = '5d66ed7b914e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('encryptedPass', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('key', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('key')
        batch_op.drop_column('encryptedPass')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
