"""empty message

Revision ID: 5d66ed7b914e
Revises: 24a649752356
Create Date: 2024-02-23 04:45:53.965725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d66ed7b914e'
down_revision = '24a649752356'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add a new column 'token' with a server default value
        batch_op.add_column(sa.Column('token', sa.String(), nullable=False, server_default='default_token'))
        batch_op.drop_column('passkey')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # When downgrading, 'token' is dropped, so 'server_default' is not relevant here
        batch_op.add_column(sa.Column('passkey', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('token')
    # ### end Alembic commands ###
